from . import claims
from . import claim_items
from . import product
from . import res_partner
from . import sale_subscription
from . import sale_order
from . import sale_coupon_program
from . import res_country_state
from . import home_warranty
from . import crm_lead
from . import account_payment
from . import account_move
from . import payment
from . import vendor_zip_codes
from . import sale_subscription_template
from . import achosa_anniversary_email
from . import token
from . import survey
from . import mail_message
from . import ir_logging
from . import res_company
from . import res_users
from . import product_pricelist
# from . import account_move_line
from . import website
from . import product_public_category
